module four_bit_adder_sva (
    input logic       clk,
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       Cin,
    input logic [3:0] S,
    input logic       C_out
);

    // Sum and carry match 4-bit addition with carry-in.
    check_total_sum: assert property (
        @(posedge clk)
        {C_out, S} == ({1'b0, A} + {1'b0, B} + Cin)
    );

    // Bit 0 sum is the XOR of A[0], B[0], and Cin.
    check_sum_bit0: assert property (
        @(posedge clk)
        S[0] == (A[0] ^ B[0] ^ Cin)
    );

    // Bit 1 sum uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk)
        S[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))
    );

    // Bit 2 sum uses the carry generated by bits 0 and 1.
    check_sum_bit2: assert property (
        @(posedge clk)
        S[2] == (A[2] ^ B[2] ^
                 ((A[1] & B[1]) |
                  (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                  (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))))
    );

    // Bit 3 sum uses the carry generated by bits 0 through 2.
    check_sum_bit3: assert property (
        @(posedge clk)
        S[3] == (A[3] ^ B[3] ^
                 ((A[2] & B[2]) |
                  (B[2] & ((A[1] & B[1]) |
                           (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                           (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))))) |
                  (A[2] & ((A[1] & B[1]) |
                           (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                           (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))))))
    );

    // Carry-out matches the final carry generated by bit 3.
    check_cout: assert property (
        @(posedge clk)
        C_out == ((A[3] & B[3]) |
                  (B[3] & ((A[2] & B[2]) |
                           (B[2] & ((A[1] & B[1]) |
                                    (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                                    (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))))) |
                           (A[2] & ((A[1] & B[1]) |
                                    (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                                    (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))))))) |
                  (A[3] & ((A[2] & B[2]) |
                           (B[2] & ((A[1] & B[1]) |
                                    (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                                    (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))))) |
                           (A[2] & ((A[1] & B[1]) |
                                    (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                                    (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))))))))
    );

endmodule