module RippleAdder2_sva (
    input logic [3:0] a,
    input logic [3:0] b,
    input logic       ci,
    input logic       co,
    input logic [3:0] s
);

    // No RTL clock or reset exists; sample the combinational DUT on $global_clock.
    // The interface is a[3:0], b[3:0], ci -> s[3:0], co.

    // The 5-bit result matches a 4-bit add with carry-in.
    check_full_sum: assert property (
        @($global_clock) {co, s} == ({1'b0, a} + {1'b0, b} + ci)
    );

    // With ci low, the result reduces to plain 4-bit addition.
    check_plain_add_without_carry_in: assert property (
        @($global_clock) (ci == 1'b0) |-> ({co, s} == ({1'b0, a} + {1'b0, b}))
    );

    // Carry-out is high exactly when the total exceeds 4 bits.
    check_carry_matches_overflow: assert property (
        @($global_clock) co == (({1'b0, a} + {1'b0, b} + ci) > 5'd15)
    );

    // Sum bit 0 is the XOR of the LSB inputs and carry-in.
    check_sum_bit0: assert property (
        @($global_clock) s[0] == (a[0] ^ b[0] ^ ci)
    );

    // Sum bit 1 uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @($global_clock)
        s[1] == (a[1] ^ b[1] ^ ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci)))
    );

    // Sum bit 2 uses the ripple carry from bits 0 and 1.
    check_sum_bit2: assert property (
        @($global_clock)
        s[2] == (
            a[2] ^ b[2] ^
            (
                (a[1] & b[1]) |
                (a[1] & ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci))) |
                (b[1] & ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci)))
            )
        )
    );

    // Adding zero on B leaves A plus the carry-in.
    check_add_zero_b: assert property (
        @($global_clock) (b == 4'b0000) |-> ({co, s} == ({1'b0, a} + ci))
    );

    // Adding zero on A leaves B plus the carry-in.
    check_add_zero_a: assert property (
        @($global_clock) (a == 4'b0000) |-> ({co, s} == ({1'b0, b} + ci))
    );

    // All-zero inputs produce an all-zero result.
    check_zero_addition: assert property (
        @($global_clock)
        ((a == 4'b0000) && (b == 4'b0000) && (ci == 1'b0)) |-> ({co, s} == 5'b00000)
    );

    // Complementary operands with ci high produce 0 with carry-out 1.
    check_complement_plus_one: assert property (
        @($global_clock)
        (((a ^ b) == 4'b1111) && (ci == 1'b1)) |-> ({co, s} == 5'b10000)
    );

endmodule