module ripple_carry_adder_sva (
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       cin,
    input logic [3:0] sum,
    input logic       cout
);

    // No RTL clock or reset; sample this combinational logic on the formal global clock.

    // The 5-bit output must equal the arithmetic sum of A, B, and cin.
    check_total_sum: assert property (
        @($global_clock)
        {cout, sum} == ({1'b0, A} + {1'b0, B} + {4'b0000, cin})
    );

    // sum[0] must match the full-adder XOR equation.
    check_sum_bit0: assert property (
        @($global_clock)
        sum[0] == (A[0] ^ B[0] ^ cin)
    );

    // sum[1] must use the carry generated by bit 0.
    check_sum_bit1: assert property (
        @($global_clock)
        sum[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))
    );

    // sum[2] must use the carry generated by bits 0 and 1.
    check_sum_bit2: assert property (
        @($global_clock)
        sum[2] == (A[2] ^ B[2] ^
                   ((A[1] & B[1]) |
                    (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                    (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))))
    );

    // sum[3] must use the carry generated by bits 0 through 2.
    check_sum_bit3: assert property (
        @($global_clock)
        sum[3] == (A[3] ^ B[3] ^
                   ((A[2] & B[2]) |
                    (A[2] & ((A[1] & B[1]) |
                             (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                             (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))))) |
                    (B[2] & ((A[1] & B[1]) |
                             (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                             (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))))))
    );

    // cout must match the final carry-out equation.
    check_cout: assert property (
        @($global_clock)
        cout == ((A[3] & B[3]) |
                 (A[3] & ((A[2] & B[2]) |
                          (A[2] & ((A[1] & B[1]) |
                                   (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                                   (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))))) |
                          (B[2] & ((A[1] & B[1]) |
                                   (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                                   (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))))))) |
                 (B[3] & ((A[2] & B[2]) |
                          (A[2] & ((A[1] & B[1]) |
                                   (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                                   (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))))) |
                          (B[2] & ((A[1] & B[1]) |
                                   (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                                   (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))))))))
    );

endmodule