module RippleCarryAdder4bit_sva (
    input logic        clk,
    input logic [3:0]  A,
    input logic [3:0]  B,
    input logic        Ci,
    input logic [3:0]  S,
    input logic        Co
);

    // Carry-out matches the 5-bit addition of A, B, and Ci.
    check_carry_matches_addition: assert property (
        @(posedge clk) Co == (({1'b0, A} + {1'b0, B} + Ci) >= 5'd16)
    );

    // Sum bit 0 is the XOR of the least-significant input bits and carry-in.
    check_sum_bit0: assert property (
        @(posedge clk) S[0] == (A[0] ^ B[0] ^ Ci)
    );

    // Sum bit 1 uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk) S[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | ((A[0] ^ B[0]) & Ci)))
    );

    // Sum bit 2 uses the ripple carry generated through bit 1.
    check_sum_bit2: assert property (
        @(posedge clk) S[2] == (A[2] ^ B[2] ^
            (
                (A[1] & B[1]) |
                (
                    (A[1] ^ B[1]) &
                    (
                        (A[0] & B[0]) |
                        ((A[0] ^ B[0]) & Ci)
                    )
                )
            )
        )
    );

    // Sum bit 3 uses the ripple carry generated through bit 2.
    check_sum_bit3: assert property (
        @(posedge clk) S[3] == (A[3] ^ B[3] ^
            (
                (A[2] & B[2]) |
                (
                    (A[2] ^ B[2]) &
                    (
                        (A[1] & B[1]) |
                        (
                            (A[1] ^ B[1]) &
                            (
                                (A[0] & B[0]) |
                                ((A[0] ^ B[0]) & Ci)
                            )
                        )
                    )
                )
            )
        )
    );

    // Carry-out is the ripple carry generated through the most-significant bit.
    check_carry_out: assert property (
        @(posedge clk) Co == (
            (A[3] & B[3]) |
            (
                (A[3] ^ B[3]) &
                (
                    (A[2] & B[2]) |
                    (
                        (A[2] ^ B[2]) &
                        (
                            (A[1] & B[1]) |
                            (
                                (A[1] ^ B[1]) &
                                (
                                    (A[0] & B[0]) |
                                    ((A[0] ^ B[0]) & Ci)
                                )
                            )
                        )
                    )
                )
            )
        )
    );

endmodule