module adder4bit_sva (
    input logic       clk,
    input logic [3:0] a,
    input logic [3:0] b,
    input logic       cin,
    input logic [3:0] sum,
    input logic       cout
);

    // Full 5-bit result matches a + b + cin.
    check_full_addition: assert property (
        @(posedge clk) {cout, sum} == ({1'b0, a} + {1'b0, b} + cin)
    );

    // Sum bit 0 matches the first full-adder XOR.
    check_sum_bit0: assert property (
        @(posedge clk) sum[0] == (a[0] ^ b[0] ^ cin)
    );

    // Sum bit 1 uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk) sum[1] == (
            a[1] ^ b[1] ^
            ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))
        )
    );

    // Sum bit 2 uses the ripple carry from bits 0 and 1.
    check_sum_bit2: assert property (
        @(posedge clk) sum[2] == (
            a[2] ^ b[2] ^
            (
                (a[1] & b[1]) |
                (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
            )
        )
    );

    // Sum bit 3 uses the ripple carry from bits 0 through 2.
    check_sum_bit3: assert property (
        @(posedge clk) sum[3] == (
            a[3] ^ b[3] ^
            (
                (a[2] & b[2]) |
                (a[2] & (
                    (a[1] & b[1]) |
                    (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                    (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
                )) |
                (b[2] & (
                    (a[1] & b[1]) |
                    (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                    (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
                ))
            )
        )
    );

    // Carry-out matches the final ripple carry from bit 3.
    check_cout: assert property (
        @(posedge clk) cout == (
            (a[3] & b[3]) |
            (a[3] & (
                (a[2] & b[2]) |
                (a[2] & (
                    (a[1] & b[1]) |
                    (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                    (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
                )) |
                (b[2] & (
                    (a[1] & b[1]) |
                    (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                    (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
                ))
            )) |
            (b[3] & (
                (a[2] & b[2]) |
                (a[2] & (
                    (a[1] & b[1]) |
                    (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                    (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
                )) |
                (b[2] & (
                    (a[1] & b[1]) |
                    (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                    (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
                ))
            ))
        )
    );

endmodule