module ripple_carry_adder_sva (
    input logic [3:0] A,
    input logic [3:0] B,
    input logic [3:0] OUT
);

    // No RTL clock or reset; sample combinational behavior on the global clock.

    // OUT must equal the 4-bit sum of A and B.
    check_out_matches_sum: assert property (
        @($global_clock) OUT == (A + B)
    );

    // Bit 0 must be the XOR of A[0] and B[0].
    check_sum_bit0: assert property (
        @($global_clock) OUT[0] == (A[0] ^ B[0])
    );

    // Bit 1 must use the carry generated by bit 0.
    check_sum_bit1: assert property (
        @($global_clock) OUT[1] == (A[1] ^ B[1] ^ (A[0] & B[0]))
    );

    // Bit 2 must use the ripple carry from bits 0 and 1.
    check_sum_bit2: assert property (
        @($global_clock) OUT[2] == (A[2] ^ B[2] ^
            ((A[1] & B[1]) | ((A[0] & B[0]) & (A[1] | B[1]))))
    );

    // Bit 3 must use the ripple carry from bits 0 through 2.
    check_sum_bit3: assert property (
        @($global_clock) OUT[3] == (A[3] ^ B[3] ^
            ((A[2] & B[2]) |
             ((A[1] & B[1]) & (A[2] | B[2])) |
             (((A[0] & B[0]) & (A[1] | B[1])) & (A[2] | B[2]))))
    );

    // Adding zero on B must pass A through unchanged.
    check_add_zero_b: assert property (
        @($global_clock) (B == 4'b0000) |-> (OUT == A)
    );

    // Adding zero on A must pass B through unchanged.
    check_add_zero_a: assert property (
        @($global_clock) (A == 4'b0000) |-> (OUT == B)
    );

    // Zero plus zero must produce zero.
    check_zero_plus_zero: assert property (
        @($global_clock) ((A == 4'b0000) && (B == 4'b0000)) |-> (OUT == 4'b0000)
    );

    // 4'hF plus 4'h1 must wrap to zero.
    check_f_plus_one_wraps: assert property (
        @($global_clock) ((A == 4'hF) && (B == 4'h1)) |-> (OUT == 4'h0)
    );

    // 4'hF plus 4'hF must produce 4'hE.
    check_f_plus_f: assert property (
        @($global_clock) ((A == 4'hF) && (B == 4'hF)) |-> (OUT == 4'hE)
    );

endmodule