module adder_4bit_sva (
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       Cin,
    input logic [3:0] S,
    input logic       Cout
);

    // Combined outputs equal the 5-bit sum of A, B, and Cin.
    check_full_sum: assert property (
        @($global_clock) {Cout, S} == ({1'b0, A} + {1'b0, B} + Cin)
    );

    // Sum bit 0 is the XOR of the least-significant input bits and Cin.
    check_sum_bit0: assert property (
        @($global_clock) S[0] == (A[0] ^ B[0] ^ Cin)
    );

    // Sum bit 1 includes the carry generated by bit 0.
    check_sum_bit1: assert property (
        @($global_clock) S[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
    );

    // Sum bit 2 includes the carry generated by bits 0 and 1.
    check_sum_bit2: assert property (
        @($global_clock) S[2] == (A[2] ^ B[2] ^ (
            (A[1] & B[1]) |
            ((A[1] | B[1]) & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
        ))
    );

    // Sum bit 3 includes the carry generated by bits 0 through 2.
    check_sum_bit3: assert property (
        @($global_clock) S[3] == (A[3] ^ B[3] ^ (
            (A[2] & B[2]) |
            ((A[2] | B[2]) & (
                (A[1] & B[1]) |
                ((A[1] | B[1]) & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
            ))
        ))
    );

    // Carry-out is the carry generated by the full 4-bit addition.
    check_cout: assert property (
        @($global_clock) Cout == (
            (A[3] & B[3]) |
            ((A[3] | B[3]) & (
                (A[2] & B[2]) |
                ((A[2] | B[2]) & (
                    (A[1] & B[1]) |
                    ((A[1] | B[1]) & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
                ))
            ))
        )
    );

endmodule