module ripple_carry_adder_sva (
    input logic       clk,
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       cin,
    input logic [3:0] sum,
    input logic       cout
);

    // Full 5-bit result matches A + B + cin.
    check_full_result: assert property (
        @(posedge clk)
        {cout, sum} == ({1'b0, A} + {1'b0, B} + cin)
    );

    // LSB sum matches the first full-adder XOR equation.
    check_lsb_sum_xor: assert property (
        @(posedge clk)
        sum[0] == (A[0] ^ B[0] ^ cin)
    );

    // Bit 1 sum uses the carry generated by bit 0.
    check_bit1_ripple_sum: assert property (
        @(posedge clk)
        sum[1] == (
            A[1] ^ B[1] ^
            ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))
        )
    );

    // Carry-out reflects overflow of the 4-bit addition.
    check_carry_out_overflow: assert property (
        @(posedge clk)
        cout == (({1'b0, A} + {1'b0, B} + cin) >= 5'd16)
    );

    // Adding zero with no carry-in passes A through unchanged.
    check_a_passthrough_when_b_zero: assert property (
        @(posedge clk)
        (B == 4'h0 && cin == 1'b0) |-> ({cout, sum} == {1'b0, A})
    );

    // Adding zero with no carry-in passes B through unchanged.
    check_b_passthrough_when_a_zero: assert property (
        @(posedge clk)
        (A == 4'h0 && cin == 1'b0) |-> ({cout, sum} == {1'b0, B})
    );

    // Zero plus zero produces only the carry-in in the LSB.
    check_zero_plus_zero_equals_cin: assert property (
        @(posedge clk)
        (A == 4'h0 && B == 4'h0) |-> ({cout, sum} == {4'b0000, cin})
    );

    // Adding a carry-in to A with B at zero increments the result by one.
    check_increment_when_b_zero_and_cin_set: assert property (
        @(posedge clk)
        (B == 4'h0 && cin == 1'b1) |-> ({cout, sum} == ({1'b0, A} + 5'd1))
    );

    // Stable inputs across samples imply stable outputs across samples.
    check_outputs_stable_when_inputs_stable: assert property (
        @(posedge clk)
        ($stable(A) && $stable(B) && $stable(cin)) |-> ($stable(sum) && $stable(cout))
    );

endmodule