module ripple_adder_32_sva (
    input logic        clk,
    input logic [31:0] a,
    input logic [31:0] b,
    input logic        cin,
    input logic [31:0] sum,
    input logic        cout
);

    // Full 33-bit result matches a + b + cin.
    check_full_addition: assert property (
        @(posedge clk) {cout, sum} == ({1'b0, a} + {1'b0, b} + cin)
    );

    // Bit 0 sum matches the first full-adder XOR.
    check_sum_bit0: assert property (
        @(posedge clk) sum[0] == (a[0] ^ b[0] ^ cin)
    );

    // Bit 1 sum uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk) sum[1] == (a[1] ^ b[1] ^ ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
    );

    // Bit 2 sum uses the ripple carry from bits 0 and 1.
    check_sum_bit2: assert property (
        @(posedge clk) sum[2] == (a[2] ^ b[2] ^
            (
                (a[1] & b[1]) |
                (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
            )
        )
    );

    // Bit 3 sum uses the ripple carry from bits 0 through 2.
    check_sum_bit3: assert property (
        @(posedge clk) sum[3] == (a[3] ^ b[3] ^
            (
                (a[2] & b[2]) |
                (a[2] & (
                    (a[1] & b[1]) |
                    (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                    (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
                )) |
                (b[2] & (
                    (a[1] & b[1]) |
                    (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                    (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
                ))
            )
        )
    );

    // Carry-out matches the final ripple carry from bit 31.
    check_cout_ripple: assert property (
        @(posedge clk) cout == (
            (a[31] & b[31]) |
            (a[31] & (
                (a[30] & b[30]) |
                (a[30] & (
                    (a[29] & b[29]) |
                    (a[29] & (
                        (a[28] & b[28]) |
                        (a[28] & (
                            (a[27] & b[27]) |
                            (a[27] & (
                                (a[26] & b[26]) |
                                (a[26] & (
                                    (a[25] & b[25]) |
                                    (a[25] & (
                                        (a[24] & b[24]) |
                                        (a[24] & (
                                            (a[23] & b[23]) |
                                            (a[23] & (
                                                (a[22] & b[22]) |
                                                (a[22] & (
                                                    (a[21] & b[21]) |
                                                    (a[21] & (
                                                        (a[20] & b[20]) |
                                                        (a[20] & (
                                                            (a[19] & b[19]) |
                                                            (a[19] & (
                                                                (a[18] & b[18]) |
                                                                (a[18] & (
                                                                    (a[17] & b[17]) |
                                                                    (a[17] & (
                                                                        (a[16] & b[16]) |
                                                                        (a[16] & (
                                                                            (a[15] & b[15]) |
                                                                            (a[15] & (
                                                                                (a[14] & b[14]) |
                                                                                (a[14] & (
                                                                                    (a[13] & b[13]) |
                                                                                    (a[13] & (
                                                                                        (a[12] & b[12]) |
                                                                                        (a[12] & (
                                                                                            (a[11] & b[11]) |
                                                                                            (a[11] & (
                                                                                                (a[10] & b[10]) |
                                                                                                (a[10] & (
                                                                                                    (a[9] & b[9]) |
                                                                                                    (a[9] & (
                                                                                                        (a[8] & b[8]) |
                                                                                                        (a[8] & (
                                                                                                            (a[7] & b[7]) |
                                                                                                            (a[7] & (
                                                                                                                (a[6] & b[6]) |
                                                                                                                (a[6] & (
                                                                                                                    (a[5] & b[5]) |
                                                                                                                    (a[5] & (
                                                                                                                        (a[4] & b[4]) |
                                                                                                                        (a[4] & (
                                                                                                                            (a[3] & b[3]) |
                                                                                                                            (a[3] & (
                                                                                                                                (a[2] & b[2]) |
                                                                                                                                (a[2] & (
                                                                                                                                    (a[1] & b[1]) |
                                                                                                                                    (a[1] & (
                                                                                                                                        (a[0] & b[0]) |
                                                                                                                                        (a[0] & cin) |
                                                                                                                                        (b[0] & cin)
                                                                                                                                    ))
                                                                                                                                ))
                                                                                                                            ))
                                                                                                                        ))
                                                                                                                    ))
                                                                                                                ))
                                                                                                            ))
                                                                                                        ))
                                                                                                    ))
                                                                                                ))
                                                                                            ))
                                                                                        ))
                                                                                    ))
                                                                                ))
                                                                            ))
                                                                        ))
                                                                    ))
                                                                ))
                                                            ))
                                                        ))
                                                    ))
                                                ))
                                            ))
                                        ))
                                    ))
                                ))
                            ))
                        ))
                    ))
                ))
            ))
        )
    );

endmodule