module adder4_sva (
    input logic [3:0] a,
    input logic [3:0] b,
    input logic       cin,
    input logic [3:0] sum,
    input logic       cout
);

    // No RTL clock or reset; sample combinational behavior on the global clock.

    // The 5-bit output must equal the arithmetic sum of a, b, and cin.
    check_full_sum: assert property (
        @($global_clock) {cout, sum} == ({1'b0, a} + {1'b0, b} + cin)
    );

    // sum[0] is the XOR of the least-significant input bits and cin.
    check_sum_bit0: assert property (
        @($global_clock) sum[0] == (a[0] ^ b[0] ^ cin)
    );

    // sum[1] includes the carry generated by bit 0.
    check_sum_bit1: assert property (
        @($global_clock) sum[1] == (a[1] ^ b[1] ^ ((a[0] & b[0]) | (cin & a[0]) | (cin & b[0])))
    );

    // sum[2] includes the ripple carry from bits 0 and 1.
    check_sum_bit2: assert property (
        @($global_clock) sum[2] == (a[2] ^ b[2] ^
            (
                (a[1] & b[1]) |
                (
                    ((a[0] & b[0]) | (cin & a[0]) | (cin & b[0])) &
                    (a[1] | b[1])
                )
            )
        )
    );

    // sum[3] includes the ripple carry from bits 0 through 2.
    check_sum_bit3: assert property (
        @($global_clock) sum[3] == (a[3] ^ b[3] ^
            (
                (a[2] & b[2]) |
                (
                    (
                        (a[1] & b[1]) |
                        (
                            ((a[0] & b[0]) | (cin & a[0]) | (cin & b[0])) &
                            (a[1] | b[1])
                        )
                    ) &
                    (a[2] | b[2])
                )
            )
        )
    );

    // cout is the final carry generated by the most-significant stage.
    check_cout: assert property (
        @($global_clock) cout == (
            (a[3] & b[3]) |
            (
                (
                    (a[2] & b[2]) |
                    (
                        (
                            (a[1] & b[1]) |
                            (
                                ((a[0] & b[0]) | (cin & a[0]) | (cin & b[0])) &
                                (a[1] | b[1])
                            )
                        ) &
                        (a[2] | b[2])
                    )
                ) &
                (a[3] | b[3])
            )
        )
    );

    // Adding zero on b with cin low passes a through unchanged.
    check_add_zero_b: assert property (
        @($global_clock) (b == 4'b0000 && cin == 1'b0) |-> ({cout, sum} == {1'b0, a})
    );

    // Adding zero on a with cin low passes b through unchanged.
    check_add_zero_a: assert property (
        @($global_clock) (a == 4'b0000 && cin == 1'b0) |-> ({cout, sum} == {1'b0, b})
    );

    // With a and b zero, cout follows cin and sum is zero.
    check_zero_inputs: assert property (
        @($global_clock) (a == 4'b0000 && b == 4'b0000) |-> (cout == cin && sum == 4'b0000)
    );

    // With a and b equal, cout is the parity of a and cin is inverted.
    check_equal_operands: assert property (
        @($global_clock) (a == b) |-> (cout == (a[0] ^ a[1] ^ a[2] ^ a[3] ^ cin) && sum == ~a)
    );

endmodule