module ripple_carry_adder_sva (
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       CIN,
    input logic [3:0] SUM,
    input logic       COUT
);

    // No RTL clock or reset; sample this combinational logic on the formal global clock.

    // SUM and COUT must match the 5-bit addition of A, B, and CIN.
    check_full_addition: assert property (
        @($global_clock) {COUT, SUM} == ({1'b0, A} + {1'b0, B} + CIN)
    );

    // Bit 0 sum must match the first full-adder XOR equation.
    check_sum_bit0: assert property (
        @($global_clock) SUM[0] == (A[0] ^ B[0] ^ CIN)
    );

    // Bit 1 sum must use the carry generated by bit 0.
    check_sum_bit1: assert property (
        @($global_clock) SUM[1] == (
            A[1] ^ B[1] ^
            ((A[0] & B[0]) | (B[0] & CIN) | (CIN & A[0]))
        )
    );

    // Bit 2 sum must use the ripple carry from bits 0 and 1.
    check_sum_bit2: assert property (
        @($global_clock) SUM[2] == (
            A[2] ^ B[2] ^
            (
                (A[1] & B[1]) |
                (
                    (A[0] & B[0]) |
                    (B[0] & CIN) |
                    (CIN & A[0])
                ) &
                (A[1] | B[1] | CIN)
            )
        )
    );

    // Bit 3 sum must use the ripple carry from bits 0 through 2.
    check_sum_bit3: assert property (
        @($global_clock) SUM[3] == (
            A[3] ^ B[3] ^
            (
                (A[2] & B[2]) |
                (
                    (A[1] & B[1]) |
                    (
                        (A[0] & B[0]) |
                        (B[0] & CIN) |
                        (CIN & A[0])
                    ) &
                    (A[1] | B[1] | CIN)
                ) &
                (A[2] | B[2] | (A[1] & B[1]) | ((A[0] & B[0]) | (B[0] & CIN) | (CIN & A[0])) | (A[1] | B[1] | CIN))
            )
        )
    );

    // Carry-out must match the final ripple-carry equation.
    check_cout_equation: assert property (
        @($global_clock) COUT == (
            (A[3] & B[3]) |
            (
                (A[2] & B[2]) |
                (
                    (A[1] & B[1]) |
                    (
                        (A[0] & B[0]) |
                        (B[0] & CIN) |
                        (CIN & A[0])
                    ) &
                    (A[1] | B[1] | CIN)
                ) &
                (A[2] | B[2] | (A[1] & B[1]) | ((A[0] & B[0]) | (B[0] & CIN) | (CIN & A[0])) | (A[1] | B[1] | CIN))
            )
        )
    );

    // Adding zero on B with no carry-in must pass A through unchanged.
    check_add_zero_b: assert property (
        @($global_clock) (B == 4'b0000 && CIN == 1'b0) |-> (SUM == A && COUT == 1'b0)
    );

    // Adding zero on A with no carry-in must pass B through unchanged.
    check_add_zero_a: assert property (
        @($global_clock) (A == 4'b0000 && CIN == 1'b0) |-> (SUM == B && COUT == 1'b0)
    );

    // With B and carry-in low, the adder must increment A by one.
    check_increment_when_b_zero: assert property (
        @($global_clock) (B == 4'b0000 && CIN == 1'b1) |-> (SUM == (A + 4'd1) && COUT == 1'b0)
    );

    // With A and carry-in low, the adder must increment B by one.
    check_increment_when_a_zero: assert property (
        @($global_clock) (A == 4'b0000 && CIN == 1'b1) |-> (SUM == (B + 4'd1) && COUT == 1'b0)
    );

    // All-zero inputs must produce all-zero outputs.
    check_zero_inputs: assert property (
        @($global_clock) (A == 4'b0000 && B == 4'b0000 && CIN == 1'b0) |-> (SUM == 4'b0000 && COUT == 1'b0)
    );

    // All-ones inputs must produce 5'b1_1111.
    check_all_ones_inputs: assert property (
        @($global_clock) (A == 4'b1111 && B == 4'b1111 && CIN == 1'b1) |-> (SUM == 4'b1111 && COUT == 1'b1)
    );

endmodule