module binary_adder_sva (
    input logic [3:0] A,
    input logic [3:0] B,
    input logic [3:0] C
);

    // C must equal the 4-bit sum of A and B.
    check_sum_matches_addition: assert property (
        @($global_clock) C == (A + B)
    );

    // Bit 0 sum is XOR of A[0], B[0], and carry-in 0.
    check_bit0_sum: assert property (
        @($global_clock) C[0] == (A[0] ^ B[0])
    );

    // Bit 1 sum uses the carry generated by bit 0.
    check_bit1_sum: assert property (
        @($global_clock) C[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0)))
    );

    // Bit 2 sum uses the carry generated by bits 0 and 1.
    check_bit2_sum: assert property (
        @($global_clock) C[2] == (A[2] ^ B[2] ^ (
            (A[1] & B[1]) |
            (A[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0))) |
            (B[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0)))
        ))
    );

    // Bit 3 sum uses the carry generated by bits 0 through 2.
    check_bit3_sum: assert property (
        @($global_clock) C[3] == (A[3] ^ B[3] ^ (
            (A[2] & B[2]) |
            (A[2] & (
                (A[1] & B[1]) |
                (A[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0))) |
                (B[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0)))
            )) |
            (B[2] & (
                (A[1] & B[1]) |
                (A[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0))) |
                (B[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0)))
            ))
        ))
    );

endmodule