module binary_adder_sva (
    input logic clk,
    input logic [3:0] A,
    input logic [3:0] B,
    input logic CIN,
    input logic [3:0] SUM,
    input logic COUT
);

// SUM[0] matches the full-adder XOR equation.
    check_sum_bit0: assert property (
        @(posedge clk) SUM[0] == (A[0] ^ B[0] ^ CIN)
    );

// SUM[1] uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk) SUM[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))
    );

// SUM[2] uses the carry generated by bit 1.
    check_sum_bit2: assert property (
        @(posedge clk) SUM[2] == (A[2] ^ B[2] ^ ((A[1] & B[1]) | (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) | (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))))
    );

// SUM[3] uses the carry generated by bit 2.
    check_sum_bit3: assert property (
        @(posedge clk) SUM[3] == (A[3] ^ B[3] ^ ((A[2] & B[2]) | (A[2] & ((A[1] & B[1]) | (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) | (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))))) | (B[2] & ((A[1] & B[1]) | (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) | (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))))))
    );

// COUT matches the full-adder carry equation.
    check_cout: assert property (
        @(posedge clk) COUT == ((A[3] & B[3]) | (A[3] & ((A[2] & B[2]) | (A[2] & ((A[1] & B[1]) | (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) | (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))))) | (B[2] & ((A[1] & B[1]) | (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) | (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))))))) | (B[3] & ((A[2] & B[2]) | (A[2] & ((A[1] & B[1]) | (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) | (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))))) | (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))))))
    );

// The 5-bit output matches the 4-bit inputs and carry-in.
    check_full_result: assert property (
        @(posedge clk) {COUT, SUM} == ({1'b0, A} + {1'b0, B} + {4'b0, CIN})
    );

endmodule
