module four_bit_adder_sva (
    input logic       clk,
    input logic [3:0] A,
    input logic [3:0] B,
    input logic [3:0] S,
    input logic       COUT
);

    // No RTL clock or reset; sample this combinational logic on clk.

    // The 5-bit output must equal the arithmetic sum of A and B.
    check_total_sum: assert property (
        @(posedge clk) {COUT, S} == ({1'b0, A} + {1'b0, B})
    );

    // Bit 0 sum must match the first full-adder XOR.
    check_sum_bit0: assert property (
        @(posedge clk) S[0] == (A[0] ^ B[0])
    );

    // Bit 1 sum must use the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk) S[1] == (A[1] ^ B[1] ^ (A[0] & B[0]))
    );

    // Bit 2 sum must use the ripple carry from bits 0 and 1.
    check_sum_bit2: assert property (
        @(posedge clk) S[2] == (A[2] ^ B[2] ^
            ((A[1] & B[1]) | (A[1] & (A[0] & B[0])) | (B[1] & (A[0] & B[0]))))
    );

    // Bit 3 sum must use the ripple carry from bits 0 through 2.
    check_sum_bit3: assert property (
        @(posedge clk) S[3] == (A[3] ^ B[3] ^
            ((A[2] & B[2]) |
             (A[2] & ((A[1] & B[1]) | (A[1] & (A[0] & B[0])) | (B[1] & (A[0] & B[0])))) |
             (B[2] & ((A[1] & B[1]) | (A[1] & (A[0] & B[0])) | (B[1] & (A[0] & B[0]))))))
    );

    // Carry-out must match the final ripple carry from bit 3.
    check_cout: assert property (
        @(posedge clk) COUT == ((A[3] & B[3]) |
            (A[3] & ((A[2] & B[2]) |
                     (A[2] & ((A[1] & B[1]) | (A[1] & (A[0] & B[0])) | (B[1] & (A[0] & B[0])))) |
                     (B[2] & ((A[1] & B[1]) | (A[1] & (A[0] & B[0])) | (B[1] & (A[0] & B[0])))))) |
            (B[3] & ((A[2] & B[2]) |
                     (A[2] & ((A[1] & B[1]) | (A[1] & (A[0] & B[0])) | (B[1] & (A[0] & B[0])))) |
                     (B[2] & ((A[1] & B[1]) | (A[1] & (A[0] & B[0])) | (B[1] & (A[0] & B[0])))))))
    );

    // Adding zero on B must pass A through with no carry.
    check_add_zero_b: assert property (
        @(posedge clk) (B == 4'b0000) |-> ({COUT, S} == {1'b0, A})
    );

    // Adding zero on A must pass B through with no carry.
    check_add_zero_a: assert property (
        @(posedge clk) (A == 4'b0000) |-> ({COUT, S} == {1'b0, B})
    );

    // Zero plus zero must produce zero with no carry.
    check_zero_plus_zero: assert property (
        @(posedge clk) ((A == 4'b0000) && (B == 4'b0000)) |-> ({COUT, S} == 5'b00000)
    );

    // 4'hF plus 4'h1 must wrap to zero with carry-out set.
    check_max_plus_one: assert property (
        @(posedge clk) ((A == 4'hF) && (B == 4'h1)) |-> ({COUT, S} == 5'b10000)
    );

endmodule