module adder_4bit_sva (
    input logic       clk,
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       Cin,
    input logic [3:0] S,
    input logic       Cout
);

    // The 5-bit output must equal the arithmetic sum of A, B, and Cin.
    check_total_sum: assert property (
        @(posedge clk) {Cout, S} == ({1'b0, A} + {1'b0, B} + Cin)
    );

    // Bit 0 sum must match the first full-adder XOR equation.
    check_sum_bit0: assert property (
        @(posedge clk) S[0] == (A[0] ^ B[0] ^ Cin)
    );

    // Bit 1 sum must use the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk) S[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
    );

    // Bit 2 sum must use the ripple carry generated through bit 1.
    check_sum_bit2: assert property (
        @(posedge clk) S[2] == (A[2] ^ B[2] ^
            (
                (A[1] & B[1]) |
                (A[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin))) |
                (B[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
            )
        )
    );

    // Bit 3 sum must use the ripple carry generated through bit 2.
    check_sum_bit3: assert property (
        @(posedge clk) S[3] == (A[3] ^ B[3] ^
            (
                (A[2] & B[2]) |
                (A[2] &
                    (
                        (A[1] & B[1]) |
                        (A[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin))) |
                        (B[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
                    )
                ) |
                (B[2] &
                    (
                        (A[1] & B[1]) |
                        (A[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin))) |
                        (B[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
                    )
                )
            )
        )
    );

    // Carry-out must match the final full-adder carry equation.
    check_cout_equation: assert property (
        @(posedge clk) Cout == (
            (A[3] & B[3]) |
            (A[3] &
                (
                    (A[2] & B[2]) |
                    (A[2] &
                        (
                            (A[1] & B[1]) |
                            (A[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin))) |
                            (B[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
                        )
                    ) |
                    (B[2] &
                        (
                            (A[1] & B[1]) |
                            (A[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin))) |
                            (B[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
                        )
                    )
                )
            ) |
            (B[3] &
                (
                    (A[2] & B[2]) |
                    (A[2] &
                        (
                            (A[1] & B[1]) |
                            (A[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin))) |
                            (B[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
                        )
                    ) |
                    (B[2] &
                        (
                            (A[1] & B[1]) |
                            (A[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin))) |
                            (B[1] & ((A[0] & B[0]) | (A[0] & Cin) | (B[0] & Cin)))
                        )
                    )
                )
            )
        )
    );

endmodule