module ripple_carry_adder_sva (
    input logic       clk,
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       cin,
    input logic [3:0] sum,
    input logic       cout
);

    // Full 5-bit result matches A + B + cin.
    check_full_addition: assert property (
        @(posedge clk) {cout, sum} == ({1'b0, A} + {1'b0, B} + cin)
    );

    // sum[0] is the XOR of the least-significant input bits and cin.
    check_sum_bit0: assert property (
        @(posedge clk) sum[0] == (A[0] ^ B[0] ^ cin)
    );

    // sum[1] uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk) sum[1] == (
            A[1] ^ B[1] ^
            ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))
        )
    );

    // sum[2] uses the ripple carry from bits 0 and 1.
    check_sum_bit2: assert property (
        @(posedge clk) sum[2] == (
            A[2] ^ B[2] ^
            (
                (A[1] & B[1]) |
                (
                    (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                    (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))
                )
            )
        )
    );

    // sum[3] uses the ripple carry from bits 0 through 2.
    check_sum_bit3: assert property (
        @(posedge clk) sum[3] == (
            A[3] ^ B[3] ^
            (
                (A[2] & B[2]) |
                (
                    (A[2] & (
                        (A[1] & B[1]) |
                        (
                            (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                            (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))
                        )
                    )) |
                    (B[2] & (
                        (A[1] & B[1]) |
                        (
                            (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                            (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))
                        )
                    ))
                )
            )
        )
    );

    // cout is the final ripple carry from the MSB stage.
    check_cout: assert property (
        @(posedge clk) cout == (
            (A[3] & B[3]) |
            (
                (A[3] & (
                    (A[2] & B[2]) |
                    (
                        (A[2] & (
                            (A[1] & B[1]) |
                            (
                                (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                                (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))
                            )
                        )) |
                        (B[2] & (
                            (A[1] & B[1]) |
                            (
                                (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                                (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))
                            )
                        ))
                    )
                )) |
                (B[3] & (
                    (A[2] & B[2]) |
                    (
                        (A[2] & (
                            (A[1] & B[1]) |
                            (
                                (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                                (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))
                            )
                        )) |
                        (B[2] & (
                            (A[1] & B[1]) |
                            (
                                (A[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin))) |
                                (B[1] & ((A[0] & B[0]) | (A[0] & cin) | (B[0] & cin)))
                            )
                        ))
                    )
                ))
            )
        )
    );

endmodule