module binary_adder_sva (
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       CIN,
    input logic [3:0] SUM,
    input logic       COUT
);

    // SUM and COUT must match the 5-bit addition of A, B, and CIN.
    check_full_addition: assert property (
        @($global_clock)
        {COUT, SUM} == ({1'b0, A} + {1'b0, B} + CIN)
    );

    // SUM bit 0 must match the XOR of the LSB inputs and carry-in.
    check_sum_bit0: assert property (
        @($global_clock)
        SUM[0] == (A[0] ^ B[0] ^ CIN)
    );

    // SUM bit 1 must use the carry generated by bit 0.
    check_sum_bit1: assert property (
        @($global_clock)
        SUM[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))
    );

    // SUM bit 2 must use the carry generated by bits 0 and 1.
    check_sum_bit2: assert property (
        @($global_clock)
        SUM[2] == (A[2] ^ B[2] ^ (
            (A[1] & B[1]) |
            (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) |
            (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))
        ))
    );

    // SUM bit 3 must use the carry generated by bits 0 through 2.
    check_sum_bit3: assert property (
        @($global_clock)
        SUM[3] == (A[3] ^ B[3] ^ (
            (A[2] & B[2]) |
            (A[2] & (
                (A[1] & B[1]) |
                (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) |
                (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))
            )) |
            (B[2] & (
                (A[1] & B[1]) |
                (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) |
                (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))
            ))
        ))
    );

    // COUT must be the carry out of the most significant full adder stage.
    check_cout: assert property (
        @($global_clock)
        COUT == (
            (A[3] & B[3]) |
            (A[3] & (
                (A[2] & B[2]) |
                (A[2] & (
                    (A[1] & B[1]) |
                    (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) |
                    (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))
                )) |
                (B[2] & (
                    (A[1] & B[1]) |
                    (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) |
                    (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))
                ))
            )) |
            (B[3] & (
                (A[2] & B[2]) |
                (A[2] & (
                    (A[1] & B[1]) |
                    (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) |
                    (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))
                )) |
                (B[2] & (
                    (A[1] & B[1]) |
                    (A[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN))) |
                    (B[1] & ((A[0] & B[0]) | (A[0] & CIN) | (B[0] & CIN)))
                ))
            ))
        )
    );

endmodule