module adder_sva (
    input logic clk,
    input logic [3:0] A,
    input logic [3:0] B,
    input logic [3:0] C,
    input logic CO
);

// Sum must equal A + B.
    check_total_sum: assert property (
        @(posedge clk) disable iff (1'b0) {CO, C} == ({1'b0, A} + {1'b0, B})
    );

// LSB of C must equal A[0] ^ B[0].
    check_lsb_xor: assert property (
        @(posedge clk) disable iff (1'b0) C[0] == (A[0] ^ B[0])
    );

// Bit1 of C must equal A[1] ^ B[1] ^ C[0].
    check_bit1_xor: assert property (
        @(posedge clk) disable iff (1'b0) C[1] == (A[1] ^ B[1] ^ C[0])
    );

// Bit2 of C must equal A[2] ^ B[2] ^ C[1].
    check_bit2_xor: assert property (
        @(posedge clk) disable iff (1'b0) C[2] == (A[2] ^ B[2] ^ C[1])
    );

// Bit3 of C must equal A[3] ^ B[3] ^ C[2].
    check_bit3_xor: assert property (
        @(posedge clk) disable iff (1'b0) C[3] == (A[3] ^ B[3] ^ C[2])
    );

// Carry-out must equal the carry generated by the 4-bit addition.
    check_carry_out: assert property (
        @(posedge clk) disable iff (1'b0) CO == (({1'b0, A} + {1'b0, B}) > 5'd15)
    );

// 0 + 0 must produce 0 with no carry.
    check_zero_plus_zero: assert property (
        @(posedge clk) disable iff (1'b0) (A == 4'h0 && B == 4'h0) |-> ({CO, C} == 5'h00)
    );

// 0 + 15 must produce 15 with no carry.
    check_zero_plus_max: assert property (
        @(posedge clk) disable iff (1'b0) (A == 4'h0 && B == 4'hF) |-> ({CO, C} == 5'hF0)
    );

// 15 + 0 must produce 15 with no carry.
    check_max_plus_zero: assert property (
        @(posedge clk) disable iff (1'b0) (A == 4'hF && B == 4'h0) |-> ({CO, C} == 5'hF0)
    );

// 15 + 15 must produce 30 with carry-out.
    check_max_plus_max: assert property (
        @(posedge clk) disable iff (1'b0) (A == 4'hF && B == 4'hF) |-> ({CO, C} == 5'h1E)
    );

endmodule
