module binary_adder_sva (
    input logic [3:0] A,
    input logic [3:0] B,
    input logic [3:0] C
);

    // C[0] is the XOR of A[0], B[0], and the implicit zero carry-in.
    check_sum_bit0: assert property (
        @($global_clock) C[0] == (A[0] ^ B[0])
    );

    // C[1] uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @($global_clock)
        C[1] == (A[1] ^ B[1] ^
                 ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0)))
    );

    // C[2] uses the carry generated by bits 0 and 1.
    check_sum_bit2: assert property (
        @($global_clock)
        C[2] == (A[2] ^ B[2] ^
                 ((A[1] & B[1]) |
                  (A[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0))) |
                  (B[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0))))))
    );

    // C[3] uses the carry generated by bits 0 through 2.
    check_sum_bit3: assert property (
        @($global_clock)
        C[3] == (A[3] ^ B[3] ^
                 ((A[2] & B[2]) |
                  (A[2] & ((A[1] & B[1]) |
                           (A[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0))) |
                           (B[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0)))))) |
                  (B[2] & ((A[1] & B[1]) |
                           (A[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0))) |
                           (B[1] & ((A[0] & B[0]) | (A[0] & 1'b0) | (B[0] & 1'b0))))))))
    );

    // C matches the 4-bit sum of A and B.
    check_full_sum: assert property (
        @($global_clock) C == (A + B)
    );

endmodule