module RippleAdder2_sva #(
    parameter int p_wordlength = 4
) (
    input logic [3:0] a,
    input logic [3:0] b,
    input logic       ci,
    input logic       co,
    input logic [3:0] s
);

    // No RTL clock or reset; sample this combinational adder on $global_clock.

    // The 5-bit output must equal the zero-extended sum of a, b, and ci.
    check_total_sum: assert property (
        @($global_clock)
        {co, s} == ({1'b0, a} + {1'b0, b} + {4'b0000, ci})
    );

    // Bit 0 must be the XOR of the least-significant input bits and ci.
    check_lsb_sum: assert property (
        @($global_clock)
        s[0] == (a[0] ^ b[0] ^ ci)
    );

    // Bit 1 must include the carry generated by bit 0.
    check_bit1_sum: assert property (
        @($global_clock)
        s[1] == (a[1] ^ b[1] ^ ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci)))
    );

    // Bit 2 must include the carry generated by bits 0 and 1.
    check_bit2_sum: assert property (
        @($global_clock)
        s[2] == (a[2] ^ b[2] ^
                 ((a[1] & b[1]) |
                  (a[1] & ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci))) |
                  (b[1] & ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci)))))
    );

    // Bit 3 must include the carry generated by bits 0 through 2.
    check_bit3_sum: assert property (
        @($global_clock)
        s[3] == (a[3] ^ b[3] ^
                 ((a[2] & b[2]) |
                  (a[2] & ((a[1] & b[1]) |
                           (a[1] & ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci))) |
                           (b[1] & ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci))))) |
                  (b[2] & ((a[1] & b[1]) |
                           (a[1] & ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci))) |
                           (b[1] & ((a[0] & b[0]) | (a[0] & ci) | (b[0] & ci)))))))
    );

    // Carry-out must be high exactly when the 4-bit addition overflows.
    check_carry_out: assert property (
        @($global_clock)
        co == (({1'b0, a} + {1'b0, b} + {4'b0000, ci}) >= 5'd16)
    );

    // With b and ci low, the adder must pass a through unchanged.
    check_pass_a_when_b_and_ci_zero: assert property (
        @($global_clock)
        ((b == 4'h0) && (ci == 1'b0)) |-> ((s == a) && (co == 1'b0))
    );

    // With a and ci low, the adder must pass b through unchanged.
    check_pass_b_when_a_and_ci_zero: assert property (
        @($global_clock)
        ((a == 4'h0) && (ci == 1'b0)) |-> ((s == b) && (co == 1'b0))
    );

    // With a and b low, the adder must increment ci by one.
    check_increment_ci_when_a_and_b_zero: assert property (
        @($global_clock)
        ((a == 4'h0) && (b == 4'h0)) |-> ((s == {3'b000, ci + 1'b1}) && (co == 1'b0))
    );

    // With a and b at 4'hF, the adder must produce 4'h0 with carry-out set.
    check_overflow_when_a_and_b_max: assert property (
        @($global_clock)
        ((a == 4'hF) && (b == 4'hF)) |-> ((s == 4'h0) && (co == 1'b1))
    );

endmodule