module four_bit_adder_sva (
    input logic clk,
    input logic [3:0] a,
    input logic [3:0] b,
    input logic cin,
    input logic [3:0] sum,
    input logic cout
);

// Sum and carry match the 5-bit addition of a, b, and cin.
    check_full_add_result: assert property (
        @(posedge clk) {cout, sum} == ({1'b0, a} + {1'b0, b} + cin)
    );

// Sum bit 0 is the XOR of the LSB inputs and carry-in.
    check_sum_bit0: assert property (
        @(posedge clk) sum[0] == (a[0] ^ b[0] ^ cin)
    );

// Sum bit 1 uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk) sum[1] == (a[1] ^ b[1] ^ ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))
    );

// Sum bit 2 uses the carry generated by bits 0 and 1.
    check_sum_bit2: assert property (
        @(posedge clk) sum[2] == (a[2] ^ b[2] ^
            ((a[1] & b[1]) | (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
            (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin)))))
    );

// Sum bit 3 uses the carry generated by bits 0 through 2.
    check_sum_bit3: assert property (
        @(posedge clk) sum[3] == (a[3] ^ b[3] ^
            ((a[2] & b[2]) | (a[2] & ((a[1] & b[1]) | (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                                   (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))))) |
            (b[2] & ((a[1] & b[1]) | (a[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))) |
                                   (b[1] & ((a[0] & b[0]) | (a[0] & cin) | (b[0] & cin))))))
    );

// Carry-out is high exactly when the 5-bit result exceeds 4 bits.
    check_cout_threshold: assert property (
        @(posedge clk) cout == (({1'b0, a} + {1'b0, b} + cin) > 5'd15)
    );

// Zero plus zero with no carry-in produces zero.
    check_zero_plus_zero: assert property (
        @(posedge clk) (a == 4'h0 && b == 4'h0 && cin == 1'b0) |-> ({cout, sum} == 5'h00)
    );

// Adding zero with no carry-in passes a through unchanged.
    check_zero_passthrough_a: assert property (
        @(posedge clk) (b == 4'h0 && cin == 1'b0) |-> ({cout, sum} == {1'b0, a})
    );

// Adding zero with no carry-in passes b through unchanged.
    check_zero_passthrough_b: assert property (
        @(posedge clk) (a == 4'h0 && cin == 1'b0) |-> ({cout, sum} == {1'b0, b})
    );

// Maximum inputs produce 5'hF with carry-out asserted.
    check_max_plus_max: assert property (
        @(posedge clk) (a == 4'hF && b == 4'hF && cin == 1'b1) |-> ({cout, sum} == 5'hF)
    );

endmodule
