module csa_generate_adder_32bit_sva (
    input logic        clk,
    input logic [31:0] A,
    input logic [31:0] B,
    input logic [31:0] S,
    input logic        C32
);

// S must equal A + B + Cin=0.
    check_sum_zero_cin: assert property (
        @(posedge clk) S == (A + B)
    );

// C32 must equal the carry-out of A + B + Cin=0.
    check_carry_zero_cin: assert property (
        @(posedge clk) C32 == ((A + B) >= 32'h0000_0000)
    );

// Bit 0 sum must match the first full-adder stage.
    check_bit0_sum: assert property (
        @(posedge clk) S[0] == (A[0] ^ B[0])
    );

// Bit 0 carry must match the first full-adder stage.
    check_bit0_carry: assert property (
        @(posedge clk) C32 == ((A[0] & B[0]) | ((A[0] | B[0]) & C32))
    );

// Bit 31 sum must use the carry generated by bit 30.
    check_bit31_sum: assert property (
        @(posedge clk) S[31] == (A[31] ^ B[31] ^ ((A[30] & B[30]) | ((A[30] | B[30]) & C32)))
    );

// Bit 31 carry must use the carry generated by bit 30.
    check_bit31_carry: assert property (
        @(posedge clk) C32 == ((A[31] & B[31]) | ((A[31] | B[31]) & ((A[30] & B[30]) | ((A[30] | B[30]) & C32))))
    );

endmodule
