module ripple_carry_adder_sva (
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       CI,
    input logic [3:0] S,
    input logic       CO
);

    // Full 5-bit result matches A + B + CI.
    check_full_addition: assert property (
        @($global_clock)
        {CO, S} == ({1'b0, A} + {1'b0, B} + CI)
    );

    // Bit 0 sum matches the first ripple stage.
    check_sum_bit0: assert property (
        @($global_clock)
        S[0] == (A[0] ^ B[0] ^ CI)
    );

    // Bit 1 sum uses the carry generated by bit 0.
    check_sum_bit1: assert property (
        @($global_clock)
        S[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI)))
    );

    // Bit 2 sum uses the carry generated by bit 1.
    check_sum_bit2: assert property (
        @($global_clock)
        S[2] == (A[2] ^ B[2] ^ (
            (A[1] & B[1]) |
            (B[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI))) |
            (A[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI)))
        ))
    );

    // Bit 3 sum uses the carry generated by bit 2.
    check_sum_bit3: assert property (
        @($global_clock)
        S[3] == (A[3] ^ B[3] ^ (
            (A[2] & B[2]) |
            (B[2] & (
                (A[1] & B[1]) |
                (B[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI))) |
                (A[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI)))
            )) |
            (A[2] & (
                (A[1] & B[1]) |
                (B[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI))) |
                (A[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI)))
            ))
        ))
    );

    // Carry-out matches the final ripple stage.
    check_carry_out: assert property (
        @($global_clock)
        CO == (
            (A[3] & B[3]) |
            (B[3] & (
                (A[2] & B[2]) |
                (B[2] & (
                    (A[1] & B[1]) |
                    (B[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI))) |
                    (A[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI)))
                )) |
                (A[2] & (
                    (A[1] & B[1]) |
                    (B[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI))) |
                    (A[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI)))
                ))
            )) |
            (A[3] & (
                (A[2] & B[2]) |
                (B[2] & (
                    (A[1] & B[1]) |
                    (B[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI))) |
                    (A[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI)))
                )) |
                (A[2] & (
                    (A[1] & B[1]) |
                    (B[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI))) |
                    (A[1] & ((A[0] & B[0]) | (B[0] & CI) | (A[0] & CI)))
                ))
            ))
        )
    );

endmodule