module csa_generate_adder_32bit_sva (
    input logic        clk,
    input logic [31:0] A,
    input logic [31:0] B,
    input logic [31:0] S,
    input logic        C32
);

    // No RTL clock or reset; clk is an external sampling clock.

    // The top-level output is the sum of A and B.
    check_top_sum: assert property (
        @(posedge clk) disable iff (1'b0)
        {C32, S} == ({1'b0, A} + {1'b0, B})
    );

    // The top-level carry-out is the carry generated by adding A and B.
    check_top_carry: assert property (
        @(posedge clk) disable iff (1'b0)
        C32 == (({1'b0, A} + {1'b0, B})[32])
    );

    // The first ripple-carry stage adds A, B, and Cin=0.
    check_stage1_sum: assert property (
        @(posedge clk) disable iff (1'b0)
        {1'b0, $past(S)} == ({1'b0, $past(A)} + {1'b0, $past(B)})
    );

    // The second ripple-carry stage adds the stage1 sum, P, and Cin=G[31].
    check_stage2_sum: assert property (
        @(posedge clk) disable iff (1'b0)
        {1'b0, $past(S)} == ({1'b0, $past(S)} + {1'b0, $past({A ^ B})} + {{31{1'b0}}, $past((A[31] & B[31]))})
    );

    // The second stage carry-out is the carry generated by that addition.
    check_stage2_carry: assert property (
        @(posedge clk) disable iff (1'b0)
        $past(C32) == (({1'b0, $past(S)} + {1'b0, $past({A ^ B})} + {{31{1'b0}}, $past((A[31] & B[31]))})[32])
    );

    // The top-level carry-out matches the second-stage carry-out.
    check_carry_propagation: assert property (
        @(posedge clk) disable iff (1'b0)
        C32 == $past(C32)
    );

    // The top-level sum matches the second-stage sum.
    check_sum_propagation: assert property (
        @(posedge clk) disable iff (1'b0)
        S == $past(S)
    );

endmodule