module ripple_carry_adder_sva (
    input logic        clk,
    input logic [7:0]  a,
    input logic [7:0]  b,
    input logic [8:0]  sum
);

    // Sum matches the 9-bit arithmetic result of a + b.
    check_sum_matches_addition: assert property (
        @(posedge clk) sum == ({1'b0, a} + {1'b0, b})
    );

    // Bit 0 sum is the XOR of a[0], b[0], and the hard-wired carry-in.
    check_sum_bit0: assert property (
        @(posedge clk) sum[0] == (a[0] ^ b[0])
    );

    // Bit 1 sum includes the carry generated by bit 0.
    check_sum_bit1: assert property (
        @(posedge clk) sum[1] == (a[1] ^ b[1] ^ (a[0] & b[0]))
    );

    // Bit 2 sum includes the ripple carry from bits 0 and 1.
    check_sum_bit2: assert property (
        @(posedge clk) sum[2] == (a[2] ^ b[2] ^
                                 ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0]))))
    );

    // Bit 3 sum includes the ripple carry from bits 0 through 2.
    check_sum_bit3: assert property (
        @(posedge clk) sum[3] == (a[3] ^ b[3] ^
                                 ((a[2] & b[2]) |
                                  (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                  (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0]))))))
    );

    // Bit 4 sum includes the ripple carry from bits 0 through 3.
    check_sum_bit4: assert property (
        @(posedge clk) sum[4] == (a[4] ^ b[4] ^
                                 ((a[3] & b[3]) |
                                  (a[3] & ((a[2] & b[2]) |
                                           (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                           (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))))) |
                                  (b[3] & ((a[2] & b[2]) |
                                           (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                           (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0]))))))))
    );

    // Bit 5 sum includes the ripple carry from bits 0 through 4.
    check_sum_bit5: assert property (
        @(posedge clk) sum[5] == (a[5] ^ b[5] ^
                                 ((a[4] & b[4]) |
                                  (a[4] & ((a[3] & b[3]) |
                                           (a[3] & ((a[2] & b[2]) |
                                                    (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                                    (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))))) |
                                           (b[3] & ((a[2] & b[2]) |
                                                    (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                                    (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))))))) |
                                  (b[4] & ((a[3] & b[3]) |
                                           (a[3] & ((a[2] & b[2]) |
                                                    (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                                    (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))))) |
                                           (b[3] & ((a[2] & b[2]) |
                                                    (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                                    (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0]))))))))))
    );

    // Bit 6 sum includes the ripple carry from bits 0 through 5.
    check_sum_bit6: assert property (
        @(posedge clk) sum[6] == (a[6] ^ b[6] ^
                                 ((a[5] & b[5]) |
                                  (a[5] & ((a[4] & b[4]) |
                                           (a[4] & ((a[3] & b[3]) |
                                                    (a[3] & ((a[2] & b[2]) |
                                                             (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                                             (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))))) |
                                                    (b[3] & ((a[2] & b[2]) |
                                                             (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                                             (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))))))) |
                                           (b[4] & ((a[3] & b[3]) |
                                                    (a[3] & ((a[2] & b[2]) |
                                                             (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                                             (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))))) |
                                                    (b[3] & ((a[2] & b[2]) |
                                                             (a[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))) |
                                                             (b[2] & ((a[1] & b[1]) | (a[1] & (a[0] & b[0])) | (b[1] & (a[0] & b[0])))))))) |
                                           (b[5] & ((a[4] & b[4]) |
                                                    (a[4] & ((a[3] & b[3]) |
                                                             (a[3] & ((a[2]