module four_bit_adder_sva (
    input logic       clk,
    input logic [3:0] A,
    input logic [3:0] B,
    input logic       Cin,
    input logic [3:0] S,
    input logic       C_out
);

    // Sum bit 0 matches the full-adder XOR equation.
    check_sum_bit0_xor: assert property (
        @(posedge clk)
        S[0] == (A[0] ^ B[0] ^ Cin)
    );

    // Sum bit 1 uses the carry generated by bit 0.
    check_sum_bit1_uses_carry0: assert property (
        @(posedge clk)
        S[1] == (A[1] ^ B[1] ^ ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))
    );

    // Sum bit 2 uses the carry generated by bit 1.
    check_sum_bit2_uses_carry1: assert property (
        @(posedge clk)
        S[2] == (A[2] ^ B[2] ^
                 ((A[1] & B[1]) |
                  (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                  (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))))))
    );

    // Sum bit 3 uses the carry generated by bit 2.
    check_sum_bit3_uses_carry2: assert property (
        @(posedge clk)
        S[3] == (A[3] ^ B[3] ^
                 ((A[2] & B[2]) |
                  (B[2] & ((A[1] & B[1]) |
                           (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                           (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))))) |
                  (A[2] & ((A[1] & B[1]) |
                           (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                           (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))))))))))
    );

    // Final carry-out matches the full-adder carry equation.
    check_cout_matches_full_adder: assert property (
        @(posedge clk)
        C_out == ((A[3] & B[3]) |
                  (B[3] & ((A[2] & B[2]) |
                           (B[2] & ((A[1] & B[1]) |
                                    (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                                    (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))))) |
                           (A[2] & ((A[1] & B[1]) |
                                    (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                                    (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))))))))) |
                  (A[3] & ((A[2] & B[2]) |
                           (B[2] & ((A[1] & B[1]) |
                                    (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                                    (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))))) |
                           (A[2] & ((A[1] & B[1]) |
                                    (B[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin))) |
                                    (A[1] & ((A[0] & B[0]) | (B[0] & Cin) | (A[0] & Cin)))))))))))
    );

    // The 5-bit output matches the arithmetic sum of A, B, and Cin.
    check_total_sum_matches_addition: assert property (
        @(posedge clk)
        {C_out, S} == ({1'b0, A} + {1'b0, B} + Cin)
    );

endmodule